### PR TITLE
Improve OpenConfig translator

### PR DESCRIPTION
**Pull request by noguchiko**
This PR improves fetures of the OpenConfig translator.

It supports;

- more `openconfig-interfaces` model nodes
- `openconfig-platform` model
- `openconfig-terminal-device` model

### CODE REVIEW

**Comment by noguchiko** [comment]
The CI workflow failed because the container image push failed.

```
#50 pushing layers
#50 ...

#51 [auth] oopt-goldstone/mgmt/builder:pull,push token for ghcr.io
#51 DONE 0.0s

#50 exporting to image
#50 pushing layers 0.6s done
#50 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: unexpected status: 403 Forbidden
```

The CI workflow [uses my (PR author's) credential](https://github.com/oopt-goldstone/goldstone-mgmt/blob/master/.github/workflows/build_image.yaml#L58-L63) to push images to `ghcr.io/oopt-goldstone/mgmt`, but it fails because I don't have permission.

@ishidawataru Could you give me permission to push images to the registry to run the CI workflow?

**Comment by ishidawataru** [comment]
@noguchiko Yes, I'll investigate what is the best practice to handle this.

**Comment by ishidawataru** [comment]
It looks like using `pull_request_target` with manual labeling to trigger the workflow is the way to go.

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

> Add a condition to the pull_request_target to run only if a certain label is assigned the PR, like safe to test that indicates the PR has been vetted by someone with write privileges to the target repository.

I added [this change](https://github.com/oopt-goldstone/goldstone-mgmt/commit/dd1752793c9c11c855b0bed684af562aa3120e37) to fix the issue.

Please rebase on the current master.

**Comment by noguchiko** [comment]
@ishidawataru Thank you for the workflow change. It appears to have worked fine!

**Comment by noguchiko** [comment]
@ishidawataru This PR is now ready for review. Could you please review the changes?

**Review by ishidawataru — APPROVED** [review]

**Pull request merged**
